import { CheckupCardType, PackageCardType } from './src/types';

export const selectOptions = [
  { label: 'Popularity', value: 'popularity' },
  { label: 'Price: Low to High', value: 'price' },
  { label: 'Rating', value: 'rating' },
  { label: 'Relevance', value: 'relevance' },
  { label: 'Discount', value: 'discount' },
];
export const dummyBrands = [
  { label: 'Dabur', value: 'dabur' },
  { label: 'Himalaya', value: 'himalaya' },
  { label: 'Baidyanath', value: 'baidyanath' },
  { label: 'Zandu', value: 'zandu' },
  { label: 'Sun Pharma', value: 'Sun Pharma' },

];
export const dummyPackagesCategories = [
  { label: 'Health checkups', value: 'Healthcheckups' },
  { label: 'Heart health tests', value: 'Heart health tests' },
  { label: 'Liver health tests', value: 'Liver health tests' },
  { label: 'Kids health tests ', value: 'Kids health tests ' },
  { label: 'Fever', value: 'Fever' },
  { label: 'Women health', value: 'Women health' },
  { label: 'Diabetes', value: 'Diabetes' },
  { label: 'Pregnancy', value: 'Pregnancy' },
];
export const dummyProductsForms = [
  { label: 'Tablet', value: 'tablet' },
  { label: 'Powder', value: 'powder' },
  { label: 'Capsule', value: 'capsule' },
  { label: 'Syrup', value: 'syrup' },
  { label: 'Cream', value: 'cream' },
];

export const dummyUses = [
  { label: 'Skin Care', value: 'skin-care' },
  { label: 'Hair Care', value: 'hair-care' },
  { label: 'Immunity Booster', value: 'immunity-booster' },
  { label: 'Weight Management', value: 'weight-management' },
];
export const dummyAges = [
  { label: 'All', value: 'all' },
  { label: 'Child', value: 'child' },
  { label: 'Adult', value: 'adult' },
  { label: 'Elderly', value: 'elderly' },
];

export const checkupCardData: CheckupCardType[] = [
  {
    id: 0,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report 1',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 1,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report 2',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 2,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report 3',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 3,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report 4',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 4,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 5,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 6,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 7,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 8,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 9,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 10,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
  {
    id: 11,
    imgUrl: '/media/labtestcard.png',
    title: 'Comprehensive gold full body checkup with smart report',
    actualPrice: 2900,
    sellingPrice: 1900,
    description: 'Get reports within 18 hrs',
  },
];
export const packageData: PackageCardType[] = [
  {
    id: 0,
    imgUrl: '/media/packagea.png',
    title: 'Health Checkups',
  },
  {
    id: 1,
    imgUrl: '/media/packageb.png',
    title: 'Heart health tests',
  },
  {
    id: 2,
    imgUrl: '/media/packagea.png',
    title: 'Liver health tests',
  },
  {
    id: 3,
    imgUrl: '/media/packageb.png',
    title: 'Kids health tests',
  },
  {
    id: 4,
    imgUrl: '/media/packagea.png',
    title: 'Health Checkups',
  },
  {
    id: 5,
    imgUrl: '/media/packageb.png',
    title: 'Heart health tests',
  },
  {
    id: 6,
    imgUrl: '/media/packagea.png',
    title: 'Liver health tests',
  },
  {
    id: 7,
    imgUrl: '/media/packageb.png',
    title: 'Kids health tests',
  },
  {
    id: 8,
    imgUrl: '/media/packagea.png',
    title: 'Health Checkups',
  },
  {
    id: 9,
    imgUrl: '/media/packageb.png',
    title: 'Heart health tests',
  },
  {
    id: 10,
    imgUrl: '/media/packagea.png',
    title: 'Liver health tests',
  },
  {
    id: 11,
    imgUrl: '/media/packageb.png',
    title: 'Kids health tests',
  },
];

export const ratingDummyData = {
  total_ratings: 28,
  avg_rating: 3.67,
  total_recommended: 17,
  rates: {
    1: 1,
    2: 5,
    3: 6,
    4: 6,
    5: 10,
  },
};

export const dummyPopularLabTestData = [
  {
    id: 1,
    imgUrl: '/LabTestDummy.png',
    title: 'Comprehensive gold full body checkup with smart report 1',
    price: 2900,
    description: 'Contains 3 tests',
  },
  {
    id: 2,
    imgUrl: '/LabTestheart.png',
    title: 'Thyroid profile total(T3,T4& TSH)',
    price: 2900,
    description: 'Contains 3 tests',
  },
  {
    id: 3,
    imgUrl: '/LabTestDummy.png',
    title: 'Comprehensive gold full body checkup with smart report 1',
    price: 2900,
    description: 'Contains 3 tests',
  },
  {
    id: 4,
    imgUrl: '/LabTestheart.png',
    title: 'Thyroid profile total(T3,T4& TSH)',
    price: 2900,
    description: 'Contains 3 tests',
  },
  // {
  //   id: 5,
  //   imgUrl: '/LabTestDummy.png',
  //   title: 'Comprehensive gold full body checkup with smart report 1',
  //   price: 2900,
  //   description: 'Contains 3 tests',
  // },
  // {
  //   id: 6,
  //   imgUrl: '/LabTestheart.png',
  //   title: 'Thyroid profile total(T3,T4& TSH)',
  //   price: 2900,
  //   description: 'Contains 3 tests',
  // },
];
export const dummyProductCardData = [
  {
    id: 0,
    imgUrl: '/dabur.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 111,
    isLiked: false,
    sellingPrice: 111,
  },
  {
    id: 1,
    imgUrl: '/productImg.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 153,
    isLiked: false,
    sellingPrice: 153,
  },
  {
    id: 2,
    imgUrl: '/tablet 1.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 150,
    isLiked: false,
    sellingPrice: 150,
  },
  {
    id: 3,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 133,
    isLiked: false,
    sellingPrice: 133,
  },
  {
    id: 4,
    imgUrl: '/dabur.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 163,
    isLiked: false,
    sellingPrice: 163,
  },
  {
    id: 5,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 169,
    isLiked: false,
    sellingPrice: 169,
  },
  {
    id: 6,
    imgUrl: '/productImg.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 197,
    isLiked: true,
    sellingPrice: 153,
  },
  {
    id: 7,
    imgUrl: '/tablet 1.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 146,
    isLiked: false,
    sellingPrice: 146,
  },
  {
    id: 8,
    imgUrl: '/dabur.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 196,
    isLiked: false,
    sellingPrice: 196,
  },
  {
    id: 9,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 148,
    isLiked: true,
    sellingPrice: 106,
  },
  {
    id: 10,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 185,
    isLiked: true,
    sellingPrice: 193,
  },
  {
    id: 11,
    imgUrl: '/productImg.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 148,
    isLiked: false,
    sellingPrice: 148,
  },
  {
    id: 12,
    imgUrl: '/dabur.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 194,
    isLiked: false,
    sellingPrice: 194,
  },
  {
    id: 13,
    imgUrl: '/productImg.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 168,
    isLiked: false,
    sellingPrice: 168,
  },
  {
    id: 14,
    imgUrl: '/productImg.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 175,
    isLiked: false,
    sellingPrice: 175,
  },
  {
    id: 15,
    imgUrl: '/tablet 1.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 119,
    isLiked: false,
    sellingPrice: 119,
  },
  {
    id: 16,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 153,
    isLiked: false,
    sellingPrice: 153,
  },
  {
    id: 17,
    imgUrl: '/image 32.png',
    title: "Protinex Mother's Chocolate Flavour Nutritional Drink Powder",
    actualPrice: 144,
    isLiked: true,
    sellingPrice: 178,
  },
];

export const dummyProductDetailData = {
  images: [
    { id: 0, url: '/tablet 1.png' },
    { id: 1, url: '/image 32.png' },
    { id: 2, url: '/productImg.png' },
    { id: 3, url: '/tablet 1.png' },
    { id: 4, url: '/dabur.png' },
    { id: 5, url: '/image 32.png' },
  ],
  name: 'Zingavita Vitamin C Zinc Effervescent Tablets Natural Amla Extract for Strong Immunity',
  manufacturer_marketer: 'Sample Manufacturer',
  return_policy: 'Sample Return Policy',
  consume_type: 'Sample Consume Type',
  variants: [
    {
      id: 1,
      name: '30 Tablets',
      price: 93,
      price_per_unit: 9.3,
      in_stock: 5,
    },
    {
      id: 2,
      name: '60 Tablets',
      price: 129,
      price_per_unit: 12.9,
      in_stock: 0,
    },
  ],
  expire: '2024-12-31',
  product_information: 'Sample Product Information',
  reviews: [
    {
      user: 'User1',
      rating: 4,
      title: 'Great product!',
      comment: 'This product exceeded my expectations.',
      is_recommended: true,
    },
    {
      user: 'User2',
      rating: 3,
      title: 'Excellent!',
      comment: 'I highly recommend this product to everyone.',
      is_recommended: true,
    },
  ],
  ratings: {
    total_ratings: 48,
    avg_rating: 1.3163894573454469,
    total_recommended: 31,
    rates: { '1': 12, '2': 18, '3': 2, '4': 7, '5': 19 },
  },
};

export const dummyAddresses = [
  {
    name: 'Home',
    street:
      'Street: C501, Vishal Apt, Behind Vishal Hall, Andheri Kurla Rd, Andheri (e)',
    city: 'Mumbai',
    state: 'Maharashtra',
    zip: '400069',
    phone: '02226833712',
  },
  {
    name: 'Office',
    street:
      'Street: C501, Vishal Apt, Behind Vishal Hall, Andheri Kurla Rd, Andheri (e)',
    city: 'Gurugram',
    state: 'Haryana',
    zip: '122022',
    phone: '999999999',
  },
];
